version: "3.9"

services:
  db:
    image: postgres:15
    container_name: pottery-db
    restart: always
    environment:
      POSTGRES_USER: pottery_user
      POSTGRES_PASSWORD: 1LoveClay!
      POSTGRES_DB: pottery
    ports:
      - "5432:5432"
    volumes:
      - pottery-db-data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: pottery-api
    restart: always
    environment:
      DATABASE_URL: postgresql://pottery_user:password@db:5432/pottery
    depends_on:
      - db
    ports:
      - "4000:4000"
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  pottery-db-data:
